"""add color and details to quotation

Revision ID: 2461a3998b27
Revises: 68d2f5bc375f
Create Date: 2026-05-14 18:26:38.973331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2461a3998b27'
down_revision: Union[str, None] = '68d2f5bc375f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation', sa.Column('colors', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation', sa.Column('additional_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation', 'additional_details')
    op.drop_column('quotation', 'colors')
    # ### end Alembic commands ###
