"""add_appointment_status_and_datetime

Revision ID: 4811fc49d34b
Revises: a7b2c9d4e5f6
Create Date: 2026-05-21 00:04:27.278963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4811fc49d34b'
down_revision: Union[str, None] = 'a7b2c9d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Set all existing dates to NULL to avoid parsing errors
    op.execute("UPDATE quotation SET appointment_date = NULL")
    
    op.add_column('quotation', sa.Column('appointment_status', sqlmodel.sql.sqltypes.AutoString(), server_default='pending', nullable=False))
    op.alter_column('quotation', 'appointment_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using="appointment_date::timestamp without time zone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotation', 'appointment_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('quotation', 'appointment_status')
    # ### end Alembic commands ###
