"""Add CMS models and mockup fields

Revision ID: 68d2f5bc375f
Revises: 9828e63ec60c
Create Date: 2026-05-14 15:15:04.798001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '68d2f5bc375f'
down_revision: Union[str, None] = '9828e63ec60c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('featured_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_post_slug'), 'blog_post', ['slug'], unique=True)
    op.create_table('gallery_image',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('studio_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_whatsapp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instagram_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hero_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hero_subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('about_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('quotation', sa.Column('mockup_x', sa.Float(), nullable=True))
    op.add_column('quotation', sa.Column('mockup_y', sa.Float(), nullable=True))
    op.add_column('quotation', sa.Column('mockup_scale', sa.Float(), nullable=True))
    op.add_column('quotation', sa.Column('mockup_rotation', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation', 'mockup_rotation')
    op.drop_column('quotation', 'mockup_scale')
    op.drop_column('quotation', 'mockup_y')
    op.drop_column('quotation', 'mockup_x')
    op.drop_table('site_settings')
    op.drop_table('gallery_image')
    op.drop_index(op.f('ix_blog_post_slug'), table_name='blog_post')
    op.drop_table('blog_post')
    # ### end Alembic commands ###
