"""expand_schema_v2

Revision ID: 9828e63ec60c
Revises: f0c383d72e4e
Create Date: 2026-05-13 21:24:15.695802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9828e63ec60c'
down_revision: Union[str, None] = 'f0c383d72e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipeline_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('ai_quote_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('items_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_cop', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mp_preference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mp_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_cop', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscription',
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('p256dh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_table('waitlist_entry',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_entry_email'), 'waitlist_entry', ['email'], unique=True)
    op.add_column('design', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('design', sa.Column('is_flash', sa.Boolean(), nullable=False))
    op.add_column('quotation', sa.Column('client_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation', sa.Column('body_zone_svg_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation', sa.Column('idea_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation', sa.Column('ai_quote_min', sa.Integer(), nullable=True))
    op.add_column('quotation', sa.Column('ai_quote_max', sa.Integer(), nullable=True))
    op.add_column('quotation', sa.Column('ai_session_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation', sa.Column('ai_sessions_count', sa.Integer(), nullable=True))
    op.add_column('quotation', sa.Column('ai_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation', sa.Column('ai_recommendation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation', sa.Column('ai_preview_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation', sa.Column('quiz_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation', sa.Column('wa_sent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation', 'wa_sent')
    op.drop_column('quotation', 'quiz_style')
    op.drop_column('quotation', 'ai_preview_image_url')
    op.drop_column('quotation', 'ai_recommendation')
    op.drop_column('quotation', 'ai_description')
    op.drop_column('quotation', 'ai_sessions_count')
    op.drop_column('quotation', 'ai_session_time')
    op.drop_column('quotation', 'ai_quote_max')
    op.drop_column('quotation', 'ai_quote_min')
    op.drop_column('quotation', 'idea_description')
    op.drop_column('quotation', 'body_zone_svg_id')
    op.drop_column('quotation', 'client_email')
    op.drop_column('design', 'is_flash')
    op.drop_column('design', 'expires_at')
    op.drop_index(op.f('ix_waitlist_entry_email'), table_name='waitlist_entry')
    op.drop_table('waitlist_entry')
    op.drop_table('push_subscription')
    op.drop_table('product')
    op.drop_table('order')
    op.drop_table('lead')
    # ### end Alembic commands ###
